export const categories = ['Semua', 'Sembako', 'Minuman', 'Kebutuhan Rumah', 'Snack']

export const produkTerlaris = [
  {
    id: 1,
    name: 'Minyak Goreng 1L',
    category: 'Sembako',
    sold: 1240,
    trend: '+5.2%',
    revenue: 18600000,
    thumb: 'drink',
    bgClass: 'from-amber-200 to-orange-100',
    textClass: 'text-amber-900',
    label: 'MG',
  },
  {
    id: 2,
    name: 'Beras Premium 5kg',
    category: 'Sembako',
    sold: 850,
    trend: '+3.8%',
    revenue: 12750000,
    thumb: 'rice',
    bgClass: 'from-stone-200 to-amber-50',
    textClass: 'text-stone-800',
    label: 'BP',
  },
  {
    id: 3,
    name: 'Gula Pasir 1kg',
    category: 'Sembako',
    sold: 620,
    trend: '+2.1%',
    revenue: 9300000,
    thumb: 'rice',
    bgClass: 'from-slate-200 to-slate-50',
    textClass: 'text-slate-800',
    label: 'GP',
  },
  {
    id: 4,
    name: 'Kopi Arabika',
    category: 'Snack',
    sold: 310,
    trend: '+12.4%',
    revenue: 6820000,
    thumb: 'chips',
    bgClass: 'from-amber-900 to-amber-700',
    textClass: 'text-white',
    label: 'KA',
  },
  {
    id: 5,
    name: 'Susu UHT 1L',
    category: 'Minuman',
    sold: 450,
    trend: '+4.5%',
    revenue: 8100000,
    thumb: 'drink',
    bgClass: 'from-blue-200 to-cyan-100',
    textClass: 'text-blue-900',
    label: 'SU',
  },
]
